project:
  type: book

book:
  title: "Libro guía estadística general"
  author:
    - name: "Cristhian Quiroz"
      affiliation: "Universidad EAFIT"
  date: "6/2/2025"
  chapters:
    - index.qmd
    - capitulo_1.qmd
    - capitulo_2.qmd
    - capitulo_3.qmd
    - capitulo_4.qmd
    - references.qmd

bibliography: references.bib

lang: es
format:
  html:
    theme:
      - cosmo
      - brand


