project:
  type: book

book:
  title: "Text book: General Statistics"
  author:
    - name: "Cristhian Quiroz"
      affiliation: "EAFIT university"
  date: "6/2/2025"
  chapters:
    - index.qmd
    - chapter_0.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - references.qmd

bibliography: references.bib

lang: en
format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    thebe: true


